In [1]:
import pandas as pd

In [89]:
import numpy as np

In [2]:
dataset = pd.read_excel(r"C:\Users\AaronH\Documents\nss_data_analytics\Projects\teis-concat-dog\data\BDI3 All Evals for NSS 11-2023.xlsx")

In [3]:
dataset

,Child ID,Gender,Date of Birth,Location - Sub Level 1,Program Label,Adaptive Sum of Scaled Scores,Adaptive Developmental Quotient,Adaptive Percentile Rank,Adaptive 95% Confidence Interval,Adaptive RDI,...,Code 1,Code 2,Code 3,Code 4,Code 5,Code 6,Code 7,Code 8,Code 9,Code 10
0,44879,F,2022-09-27,Southwest,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,39/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,47795,F,2020-12-23,Greater Nashville,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,79/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54340,M,2021-06-22,First Tennessee,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,77/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,54344,F,2022-03-07,Southeast Tennessee,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,54515,M,2021-11-04,Memphis Delta,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,1990-09-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23942,SP03287,F,2023-09-25,Memphis Delta,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23943,SP03288,F,2021-05-18,South Central,BDI-3 Eligibility Evaluation,25.0,115.0,84,107-121,96/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23944,SP03289,F,2021-10-31,South Central,BDI-3 Eligibility Evaluation,21.0,103.0,58,96-110,92/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23945,SP03290,M,2020-03-25,Memphis Delta,BDI-3 Annual Evaluation,16.0,88.0,21,82-96,66/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23946,SP03291,M,2023-09-18,Greater Nashville,BDI-3 Eligibility Evaluation,11.0,105.0,63,94-114,94/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**DROP DUPLICATES

In [4]:
dataset_dups_dropped = dataset.drop_duplicates()

In [5]:
dataset_dups_dropped

,Child ID,Gender,Date of Birth,Location - Sub Level 1,Program Label,Adaptive Sum of Scaled Scores,Adaptive Developmental Quotient,Adaptive Percentile Rank,Adaptive 95% Confidence Interval,Adaptive RDI,...,Code 1,Code 2,Code 3,Code 4,Code 5,Code 6,Code 7,Code 8,Code 9,Code 10
0,44879,F,2022-09-27,Southwest,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,39/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,47795,F,2020-12-23,Greater Nashville,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,79/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54340,M,2021-06-22,First Tennessee,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,77/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,54344,F,2022-03-07,Southeast Tennessee,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,54515,M,2021-11-04,Memphis Delta,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,1990-09-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23942,SP03287,F,2023-09-25,Memphis Delta,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23943,SP03288,F,2021-05-18,South Central,BDI-3 Eligibility Evaluation,25.0,115.0,84,107-121,96/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23944,SP03289,F,2021-10-31,South Central,BDI-3 Eligibility Evaluation,21.0,103.0,58,96-110,92/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23945,SP03290,M,2020-03-25,Memphis Delta,BDI-3 Annual Evaluation,16.0,88.0,21,82-96,66/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23946,SP03291,M,2023-09-18,Greater Nashville,BDI-3 Eligibility Evaluation,11.0,105.0,63,94-114,94/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**CREATE CLEAN DATASET

In [6]:
dataset_clean = dataset_dups_dropped

**RENAME COLUMNS

In [32]:
dataset_clean.columns = dataset_clean.columns.str.replace(' ', '_')

In [40]:
dataset_clean.columns = dataset_clean.columns.str.replace('-', '_')

In [44]:
dataset_clean.columns = dataset_clean.columns.str.replace('__', '_')

**REPLACE MISSING WITH NAN

In [50]:
dataset_clean.replace('', pd.NA, inplace=True)

C:\Users\AaronH\Anaconda3\lib\site-packages\pandas\core\frame.py:4172: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

In [51]:
dataset_clean

,Child_ID,Gender,Date_of_Birth,Location_Sub_Level_1,Program_Label,Adaptive_Sum_of_Scaled_Scores,Adaptive_Developmental_Quotient,Adaptive_Percentile_Rank,Adaptive_95%_Confidence_Interval,Adaptive_RDI,...,Code_2,Code_3,Code_4,Code_5,Code_6,Code_7,Code_8,Code_9,Code_10,SAME TEST DATE
0,44879,F,2022-09-27,Southwest,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,39/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,47795,F,2020-12-23,Greater Nashville,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,79/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,54340,M,2021-06-22,First Tennessee,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,77/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,54344,F,2022-03-07,Southeast Tennessee,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,54515,M,2021-11-04,Memphis Delta,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,1990-09-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23942,SP03287,F,2023-09-25,Memphis Delta,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
23943,SP03288,F,2021-05-18,South Central,BDI-3 Eligibility Evaluation,25.0,115.0,84,107-121,96/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
23944,SP03289,F,2021-10-31,South Central,BDI-3 Eligibility Evaluation,21.0,103.0,58,96-110,92/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
23945,SP03290,M,2020-03-25,Memphis Delta,BDI-3 Annual Evaluation,16.0,88.0,21,82-96,66/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
23946,SP03291,M,2023-09-18,Greater Nashville,BDI-3 Eligibility Evaluation,11.0,105.0,63,94-114,94/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

**DROP CASES WITH NO SCORES

In [70]:
check_columns = ['Adaptive_Sum_of_Scaled_Scores', 'Social_Emotional_Sum_of_Scaled_Scores', 'Communication_Sum_of_Scaled_Scores', 'Motor_Sum_of_Scaled_Scores', 'Cognitive_Sum_of_Scaled_Scores']

In [71]:
dataset_clean.dropna(subset=check_columns, how='all', inplace=True)

C:\Users\AaronH\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [72]:
dataset_clean

,Child_ID,Gender,Date_of_Birth,Location_Sub_Level_1,Program_Label,Adaptive_Sum_of_Scaled_Scores,Adaptive_Developmental_Quotient,Adaptive_Percentile_Rank,Adaptive_95%_Confidence_Interval,Adaptive_RDI,...,Code_3,Code_4,Code_5,Code_6,Code_7,Code_8,Code_9,Code_10,SAME TEST DATE,TEST_DATE
0,44879,F,2022-09-27,Southwest,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,39/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-06-23
1,47795,F,2020-12-23,Greater Nashville,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,79/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-03-21
2,54340,M,2021-06-22,First Tennessee,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,77/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-04-06
3,54344,F,2022-03-07,Southeast Tennessee,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-02-23
4,54515,M,2021-11-04,Memphis Delta,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,1990-09-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-02-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23942,SP03287,F,2023-09-25,Memphis Delta,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-11-15
23943,SP03288,F,2021-05-18,South Central,BDI-3 Eligibility Evaluation,25.0,115.0,84,107-121,96/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-11-13
23944,SP03289,F,2021-10-31,South Central,BDI-3 Eligibility Evaluation,21.0,103.0,58,96-110,92/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-11-14
23945,SP03290,M,2020-03-25,Memphis Delta,BDI-3 Annual Evaluation,16.0,88.0,21,82-96,66/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-10-26
23946,SP03291,M,2023-09-18,Greater Nashville,BDI-3 Eligibility Evaluation,11.0,105.0,63,94-114,94/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-10-24

**CREATE SINGLE TEST DATE COLUMN

In [73]:
dataset_clean['TEST_DATE'] = dataset_clean['Adaptive_Self_Care_Date_of_Testing']

C:\Users\AaronH\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [74]:
dataset_clean

,Child_ID,Gender,Date_of_Birth,Location_Sub_Level_1,Program_Label,Adaptive_Sum_of_Scaled_Scores,Adaptive_Developmental_Quotient,Adaptive_Percentile_Rank,Adaptive_95%_Confidence_Interval,Adaptive_RDI,...,Code_3,Code_4,Code_5,Code_6,Code_7,Code_8,Code_9,Code_10,SAME TEST DATE,TEST_DATE
0,44879,F,2022-09-27,Southwest,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,39/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-06-23
1,47795,F,2020-12-23,Greater Nashville,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,79/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-03-21
2,54340,M,2021-06-22,First Tennessee,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,77/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-04-06
3,54344,F,2022-03-07,Southeast Tennessee,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-02-23
4,54515,M,2021-11-04,Memphis Delta,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,1990-09-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-02-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23942,SP03287,F,2023-09-25,Memphis Delta,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-11-15
23943,SP03288,F,2021-05-18,South Central,BDI-3 Eligibility Evaluation,25.0,115.0,84,107-121,96/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-11-13
23944,SP03289,F,2021-10-31,South Central,BDI-3 Eligibility Evaluation,21.0,103.0,58,96-110,92/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-11-14
23945,SP03290,M,2020-03-25,Memphis Delta,BDI-3 Annual Evaluation,16.0,88.0,21,82-96,66/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-10-26
23946,SP03291,M,2023-09-18,Greater Nashville,BDI-3 Eligibility Evaluation,11.0,105.0,63,94-114,94/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,2023-10-24

**CHECK FOR MISSING TEST DATES

In [ ]:
date_nan = 'TEST_DATE'

In [76]:
rows_with_nan_test_date = dataset_clean[dataset_clean[date_nan].isna()]

In [77]:
rows_with_nan_test_date[]

,Child_ID,Gender,Date_of_Birth,Location_Sub_Level_1,Program_Label,Adaptive_Sum_of_Scaled_Scores,Adaptive_Developmental_Quotient,Adaptive_Percentile_Rank,Adaptive_95%_Confidence_Interval,Adaptive_RDI,...,Code_3,Code_4,Code_5,Code_6,Code_7,Code_8,Code_9,Code_10,SAME TEST DATE,TEST_DATE
13301,549646,M,2020-05-02,Southeast Tennessee,BDI-3 Eligibility Evaluation,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaT
14721,552599,F,2022-08-27,First Tennessee,BDI-3 Eligibility Evaluation,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaT
23271,SP02616,M,2021-08-25,South Central,BDI-3 Eligibility Evaluation,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaT

In [78]:
rows_with_nan_test_date = rows_with_nan_test_date.loc[:, rows_with_nan_test_date.columns.str.contains('Date_of_Testing')]

In [79]:
rows_with_nan_test_date

,Adaptive_Self_Care_Date_of_Testing,Adaptive_Personal_Responsibility_Date_of_Testing,Social_Emotional_Adult_Interaction_Date_of_Testing,Social_Emotional_Peer_Interaction_Date_of_Testing,Social_Emotional_Self_Concept_/_Social_Role_Date_of_Testing,Communication_Receptive_Communication_Date_of_Testing,Communication_Expressive_Communication_Date_of_Testing,Motor_Gross_Motor_Date_of_Testing,Motor_Fine_Motor_Date_of_Testing,Motor_Perceptual_Motor_Date_of_Testing,Cognitive_Attention_and_Memory_Date_of_Testing,Cognitive_Reasoning_/_Academic_Skills_Date_of_Testing,Cognitive_Perception_and_Concepts_Date_of_Testing
13301,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2023-08-21,2023-08-21,2023-08-21,2023-08-21,2023-08-21,2023-08-21
14721,NaT,NaT,2023-05-09,NaT,2023-05-09,2023-05-09,2023-05-09,2023-05-09,2023-05-09,NaT,2023-05-09,NaT,2023-05-09
23271,NaT,NaT,2023-07-17,NaT,2023-07-17,NaT,2023-07-17,2023-07-17,2023-07-17,NaT,2023-07-17,NaT,NaT

**ASSIGN TEST DATE WHERE MISSING

In [81]:
dataset_clean.at[13301,'TEST_DATE']= pd.to_datetime('2023-08-21')

In [82]:
dataset_clean.at[14721,'TEST_DATE'] = pd.to_datetime('2023-05-09')

In [83]:
dataset_clean.at[23271,'TEST_DATE']= pd.to_datetime('2023-07-17')

In [84]:
rows_with_nan_test_date = dataset_clean[dataset_clean[date_nan].isna()]

**CHECK FOR MISSING TEST DATE

In [85]:
rows_with_nan_test_date

Empty DataFrame
Columns: [Child_ID, Gender, Date_of_Birth, Location_Sub_Level_1, Program_Label, Adaptive_Sum_of_Scaled_Scores, Adaptive_Developmental_Quotient, Adaptive_Percentile_Rank, Adaptive_95%_Confidence_Interval, Adaptive_RDI, Adaptive_Z_Score, Adaptive_T_Score, Adaptive_NCE, Social_Emotional_Sum_of_Scaled_Scores, Social_Emotional_Developmental_Quotient, Social_Emotional_Percentile_Rank, Social_Emotional_95%_Confidence_Interval, Social_Emotional_RDI, Social_Emotional_Z_Score, Social_Emotional_T_Score, Social_Emotional_NCE, Communication_Sum_of_Scaled_Scores, Communication_Developmental_Quotient, Communication_Percentile_Rank, Communication_95%_Confidence_Interval, Communication_RDI, Communication_Z_Score, Communication_T_Score, Communication_NCE, Motor_Sum_of_Scaled_Scores, Motor_Developmental_Quotient, Motor_Percentile_Rank, Motor_95%_Confidence_Interval, Motor_RDI, Motor_Z_Score, Motor_T_Score, Motor_NCE, Cognitive_Sum_of_Scaled_Scores, Cognitive_Developmental_Quotient, Cognitive_Percentile_Rank, Cognitive_95%_Confidence_Interval, Cognitive_RDI, Cognitive_Z_Score, Cognitive_T_Score, Cognitive_NCE, BDI_3_Total_Sum_of_Scaled_Scores, BDI_3_Total_Developmental_Quotient, BDI_3_Total_Percentile_Rank, BDI_3_Total_90%_Confidence_Interval, BDI_3_Total_95%_Confidence_Interval, BDI_3_Total_Z_Score, BDI_3_Total_T_Score, BDI_3_Total_NCE, Adaptive_Self_Care_Examiner, Adaptive_Self_Care_Date_of_Testing, Adaptive_Self_Care_RS, Adaptive_Self_Care_SS, Adaptive_Self_Care_PR, Adaptive_Self_Care_AE, Adaptive_Self_Care_RDI, Adaptive_Self_Care_CSS, Adaptive_Self_Care_CSS_90%, Adaptive_Self_Care_Z_Score, Adaptive_Self_Care_T_Score, Adaptive_Self_Care_NCE, Adaptive_Personal_Responsibility_Examiner, Adaptive_Personal_Responsibility_Date_of_Testing, Adaptive_Personal_Responsibility_RS, Adaptive_Personal_Responsibility_SS, Adaptive_Personal_Responsibility_PR, Adaptive_Personal_Responsibility_AE, Adaptive_Personal_Responsibility_RDI, Adaptive_Personal_Responsibility_CSS, Adaptive_Personal_Responsibility_CSS_90%, Adaptive_Personal_Responsibility_Z_Score, Adaptive_Personal_Responsibility_T_Score, Adaptive_Personal_Responsibility_NCE, Social_Emotional_Adult_Interaction_Examiner, Social_Emotional_Adult_Interaction_Date_of_Testing, Social_Emotional_Adult_Interaction_RS, Social_Emotional_Adult_Interaction_SS, Social_Emotional_Adult_Interaction_PR, Social_Emotional_Adult_Interaction_AE, Social_Emotional_Adult_Interaction_RDI, Social_Emotional_Adult_Interaction_CSS, Social_Emotional_Adult_Interaction_CSS_90%, Social_Emotional_Adult_Interaction_Z_Score, Social_Emotional_Adult_Interaction_T_Score, Social_Emotional_Adult_Interaction_NCE, Social_Emotional_Peer_Interaction_Examiner, Social_Emotional_Peer_Interaction_Date_of_Testing, Social_Emotional_Peer_Interaction_RS, Social_Emotional_Peer_Interaction_SS, Social_Emotional_Peer_Interaction_PR, Social_Emotional_Peer_Interaction_AE, Social_Emotional_Peer_Interaction_RDI, Social_Emotional_Peer_Interaction_CSS, Social_Emotional_Peer_Interaction_CSS_90%, Social_Emotional_Peer_Interaction_Z_Score, Social_Emotional_Peer_Interaction_T_Score, ...]
Index: []

[0 rows x 221 columns]

**CREATE AGE COLUMN

In [97]:
dataset_clean['AGE_AT_TEST_DAYS'] = dataset_clean['TEST_DATE'] - dataset_clean['Date_of_Birth']

C:\Users\AaronH\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [98]:
dataset_clean['AGE_AT_TEST_YEARS'] = (dataset_clean['TEST_DATE'].dt.year - dataset_clean['Date_of_Birth'].dt.year)

C:\Users\AaronH\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [106]:
dataset_clean

,Child_ID,Gender,Date_of_Birth,Location_Sub_Level_1,Program_Label,Adaptive_Sum_of_Scaled_Scores,Adaptive_Developmental_Quotient,Adaptive_Percentile_Rank,Adaptive_95%_Confidence_Interval,Adaptive_RDI,...,Code_7,Code_8,Code_9,Code_10,SAME TEST DATE,TEST_DATE,AGE_AT_TEST,AGE_AT_TEST_NUMERIC,AGE_AT_TEST_DAYS,AGE_AT_TEST_YEARS
0,44879,F,2022-09-27,Southwest,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,39/90,...,NaN,NaN,NaN,NaN,False,2023-06-23,269 days,0.736497,269 days,1
1,47795,F,2020-12-23,Greater Nashville,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,79/90,...,NaN,NaN,NaN,NaN,False,2023-03-21,818 days,2.239608,818 days,3
2,54340,M,2021-06-22,First Tennessee,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,77/90,...,NaN,NaN,NaN,NaN,False,2023-04-06,653 days,1.787853,653 days,2
3,54344,F,2022-03-07,Southeast Tennessee,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,False,2023-02-23,353 days,0.966481,353 days,1
4,54515,M,2021-11-04,Memphis Delta,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,1990-09-01 00:00:00,...,NaN,NaN,NaN,NaN,False,2023-02-24,477 days,1.305982,477 days,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23942,SP03287,F,2023-09-25,Memphis Delta,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,False,2023-11-15,51 days,0.139633,51 days,0
23943,SP03288,F,2021-05-18,South Central,BDI-3 Eligibility Evaluation,25.0,115.0,84,107-121,96/90,...,NaN,NaN,NaN,NaN,False,2023-11-13,909 days,2.488757,909 days,2
23944,SP03289,F,2021-10-31,South Central,BDI-3 Eligibility Evaluation,21.0,103.0,58,96-110,92/90,...,NaN,NaN,NaN,NaN,False,2023-11-14,744 days,2.037003,744 days,2
23945,SP03290,M,2020-03-25,Memphis Delta,BDI-3 Annual Evaluation,16.0,88.0,21,82-96,66/90,...,NaN,NaN,NaN,NaN,False,2023-10-26,1310 days,3.586658,1310 days,3
23946,SP03291,M,2023-09-18,Greater Nashville,BDI-3 Eligibility Evaluation,11.0,105.0,63,94-114,94/90,...,NaN,NaN,NaN,NaN,False,2023-10-24,36 days,0.098565,36 days,0

**CREATE PERCENTILE RANK COLUMN

**CREATE REGION COLUMN

In [128]:
dataset_clean['Region'] = dataset_clean['Location_Sub_Level_1']

In [129]:
dataset_clean

,Child_ID,Gender,Date_of_Birth,Location_Sub_Level_1,Program_Label,Adaptive_Sum_of_Scaled_Scores,Adaptive_Developmental_Quotient,Adaptive_Percentile_Rank,Adaptive_95%_Confidence_Interval,Adaptive_RDI,...,Code_8,Code_9,Code_10,SAME TEST DATE,TEST_DATE,AGE_AT_TEST,AGE_AT_TEST_NUMERIC,AGE_AT_TEST_DAYS,AGE_AT_TEST_YEARS,Region
0,44879,F,2022-09-27,Southwest,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,39/90,...,NaN,NaN,NaN,False,2023-06-23,269 days,0.736497,269 days,1,Southwest
1,47795,F,2020-12-23,Greater Nashville,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,79/90,...,NaN,NaN,NaN,False,2023-03-21,818 days,2.239608,818 days,3,Greater Nashville
2,54340,M,2021-06-22,First Tennessee,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,77/90,...,NaN,NaN,NaN,False,2023-04-06,653 days,1.787853,653 days,2,First Tennessee
3,54344,F,2022-03-07,Southeast Tennessee,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,False,2023-02-23,353 days,0.966481,353 days,1,Southeast Tennessee
4,54515,M,2021-11-04,Memphis Delta,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,1990-09-01 00:00:00,...,NaN,NaN,NaN,False,2023-02-24,477 days,1.305982,477 days,2,Memphis Delta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23942,SP03287,F,2023-09-25,Memphis Delta,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,False,2023-11-15,51 days,0.139633,51 days,0,Memphis Delta
23943,SP03288,F,2021-05-18,South Central,BDI-3 Eligibility Evaluation,25.0,115.0,84,107-121,96/90,...,NaN,NaN,NaN,False,2023-11-13,909 days,2.488757,909 days,2,South Central
23944,SP03289,F,2021-10-31,South Central,BDI-3 Eligibility Evaluation,21.0,103.0,58,96-110,92/90,...,NaN,NaN,NaN,False,2023-11-14,744 days,2.037003,744 days,2,South Central
23945,SP03290,M,2020-03-25,Memphis Delta,BDI-3 Annual Evaluation,16.0,88.0,21,82-96,66/90,...,NaN,NaN,NaN,False,2023-10-26,1310 days,3.586658,1310 days,3,Memphis Delta
23946,SP03291,M,2023-09-18,Greater Nashville,BDI-3 Eligibility Evaluation,11.0,105.0,63,94-114,94/90,...,NaN,NaN,NaN,False,2023-10-24,36 days,0.098565,36 days,0,Greater Nashville

**WEST TN REGION

In [130]:
dataset_clean['Region'] = dataset_clean['Region'].str.replace('Northwest','West_TN')

In [131]:
dataset_clean['Region'] = dataset_clean['Region'].str.replace('Southwest','West_TN')

In [132]:
dataset_clean['Region'] = dataset_clean['Region'].str.replace('Memphis Delta','West_TN')

**MIDDLE TN REGION

In [133]:
dataset_clean['Region'] = dataset_clean['Region'].str.replace('Upper Cumberland','Middle_TN')

In [134]:
dataset_clean['Region'] = dataset_clean['Region'].str.replace('Greater Nashville','Middle_TN')

In [135]:
dataset_clean['Region'] = dataset_clean['Region'].str.replace('South Central','Middle_TN')

**EAST TN REGION

In [136]:
dataset_clean['Region'] = dataset_clean['Region'].str.replace('First Tennessee','East_TN')

In [137]:
dataset_clean['Region'] = dataset_clean['Region'].str.replace('East Tennessee','East_TN')

In [138]:
dataset_clean['Region'] = dataset_clean['Region'].str.replace('Southeast Tennessee','East_TN')

In [140]:
dataset_clean.groupby('Region')[['Adaptive_Sum_of_Scaled_Scores','Social_Emotional_Sum_of_Scaled_Scores','Communication_Sum_of_Scaled_Scores','Motor_Sum_of_Scaled_Scores','Cognitive_Sum_of_Scaled_Scores']].mean()

,Adaptive_Sum_of_Scaled_Scores,Social_Emotional_Sum_of_Scaled_Scores,Communication_Sum_of_Scaled_Scores,Motor_Sum_of_Scaled_Scores,Cognitive_Sum_of_Scaled_Scores
Region,,,,,
East_TN,10.966923,21.485110,13.688654,22.452374,20.516397
Middle_TN,11.621834,22.313951,12.945048,22.471264,19.924354
West_TN,11.605660,23.664361,12.990145,23.235639,20.327463

**IGNORE

In [63]:
df_scaled_scores_domains = dataset_clean.filter(regex='Sum of Scaled Scores')

In [9]:
df_scaled_scores_domains.describe()

,Adaptive Sum of Scaled Scores,Social-Emotional Sum of Scaled Scores,Communication Sum of Scaled Scores,Motor Sum of Scaled Scores,Cognitive Sum of Scaled Scores,BDI-3 Total Sum of Scaled Scores
count,19493.000000,19483.000000,19469.0000,19471.000000,19481.000000,19443.000000
mean,11.412712,22.381153,13.2015,22.655334,20.220933,89.863036
std,5.822943,7.519204,6.7228,8.067995,6.955015,28.293704
min,1.000000,2.000000,2.0000,2.000000,2.000000,9.000000
25%,7.000000,17.000000,8.0000,17.000000,16.000000,71.000000
50%,11.000000,22.000000,13.0000,22.000000,20.000000,88.000000
75%,15.000000,28.000000,18.0000,28.000000,24.000000,107.000000
max,36.000000,53.000000,38.0000,50.000000,54.000000,199.000000

In [10]:
df_scaled_scores_subdomains = dataset_clean.filter(regex='SS')

In [11]:
df_scaled_scores_subdomains

,Adaptive-Self Care SS,Adaptive-Self Care CSS,Adaptive-Self Care CSS 90%,Adaptive-Personal Responsibility SS,Adaptive-Personal Responsibility CSS,Adaptive-Personal Responsibility CSS 90%,Social Emotional-Adult Interaction SS,Social Emotional-Adult Interaction CSS,Social Emotional-Adult Interaction CSS 90%,Social Emotional-Peer Interaction SS,...,Motor-Perceptual Motor CSS 90%,Cognitive-Attention and Memory SS,Cognitive-Attention and Memory CSS,Cognitive-Attention and Memory CSS 90%,Cognitive-Reasoning / Academic Skills SS,Cognitive-Reasoning / Academic Skills CSS,Cognitive-Reasoning / Academic Skills CSS 90%,Cognitive-Perception and Concepts SS,Cognitive-Perception and Concepts CSS,Cognitive-Perception and Concepts CSS 90%
0,7.0,377.0,363 - 391,NaN,NaN,NaN,14.0,478.0,470 - 485,NaN,...,NaN,7.0,423.0,413 - 432,NaN,NaN,NaN,13.0,411.0,392 - 431
1,7.0,471.0,464 - 478,9.0,484.0,476 - 493,12.0,506.0,499 - 514,9.0,...,460 - 500,9.0,482.0,473 - 491,14.0,498.0,489 - 507,7.0,437.0,421 - 453
2,8.0,466.0,459 - 474,NaN,NaN,NaN,11.0,495.0,487 - 502,NaN,...,NaN,8.0,468.0,458 - 477,NaN,NaN,NaN,7.0,426.0,408 - 444
3,13.0,449.0,439 - 459,NaN,NaN,NaN,10.0,471.0,464 - 479,NaN,...,NaN,14.0,475.0,466 - 485,NaN,NaN,NaN,10.0,411.0,392 - 431
4,5.0,412.0,397 - 426,NaN,NaN,NaN,6.0,450.0,441 - 458,NaN,...,NaN,9.0,464.0,455 - 473,NaN,NaN,NaN,10.0,426.0,408 - 444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23942,13.0,325.0,286 - 364,NaN,NaN,NaN,13.0,435.0,425 - 445,NaN,...,NaN,9.0,381.0,369 - 393,NaN,NaN,NaN,15.0,378.0,365 - 391
23943,10.0,489.0,481 - 496,15.0,513.0,506 - 520,12.0,506.0,499 - 514,13.0,...,488 - 511,13.0,502.0,494 - 511,14.0,504.0,496 - 513,14.0,499.0,491 - 508
23944,10.0,486.0,479 - 494,11.0,490.0,482 - 499,12.0,506.0,499 - 514,10.0,...,460 - 500,10.0,485.0,476 - 495,9.0,482.0,473 - 491,10.0,464.0,450 - 479
23945,6.0,489.0,481 - 496,10.0,507.0,500 - 514,8.0,492.0,484 - 500,11.0,...,513 - 537,7.0,485.0,476 - 495,8.0,498.0,489 - 507,9.0,507.0,500 - 515
23946,11.0,302.0,286 - 319,NaN,NaN,NaN,9.0,408.0,396 - 421,NaN,...,NaN,7.0,366.0,342 - 389,NaN,NaN,NaN,12.0,352.0,323 - 381

In [12]:
df_scaled_scores_subdomains_final = df_scaled_scores_subdomains.loc[:, ~df_scaled_scores_subdomains.columns.str.contains('CSS')]

In [14]:
df_scaled_scores_subdomains_final

,Adaptive-Self Care SS,Adaptive-Personal Responsibility SS,Social Emotional-Adult Interaction SS,Social Emotional-Peer Interaction SS,Social Emotional-Self Concept / Social Role SS,Communication-Receptive Communication SS,Communication-Expressive Communication SS,Motor-Gross Motor SS,Motor-Fine Motor SS,Motor-Perceptual Motor SS,Cognitive-Attention and Memory SS,Cognitive-Reasoning / Academic Skills SS,Cognitive-Perception and Concepts SS
0,7.0,NaN,14.0,NaN,15.0,8.0,9.0,7.0,9.0,NaN,7.0,NaN,13.0
1,7.0,9.0,12.0,9.0,11.0,10.0,9.0,7.0,13.0,11.0,9.0,14.0,7.0
2,8.0,NaN,11.0,NaN,6.0,7.0,7.0,11.0,12.0,NaN,8.0,NaN,7.0
3,13.0,NaN,10.0,NaN,11.0,8.0,8.0,5.0,12.0,NaN,14.0,NaN,10.0
4,5.0,NaN,6.0,NaN,5.0,5.0,5.0,3.0,8.0,NaN,9.0,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23942,13.0,NaN,13.0,NaN,12.0,12.0,12.0,11.0,15.0,NaN,9.0,NaN,15.0
23943,10.0,15.0,12.0,13.0,13.0,14.0,10.0,15.0,11.0,12.0,13.0,14.0,14.0
23944,10.0,11.0,12.0,10.0,9.0,4.0,1.0,11.0,10.0,11.0,10.0,9.0,10.0
23945,6.0,10.0,8.0,11.0,6.0,7.0,5.0,9.0,10.0,11.0,7.0,8.0,9.0
23946,11.0,NaN,9.0,NaN,10.0,8.0,12.0,8.0,12.0,NaN,7.0,NaN,12.0

In [15]:
df_scaled_scores_subdomains_final.describe()

,Adaptive-Self Care SS,Adaptive-Personal Responsibility SS,Social Emotional-Adult Interaction SS,Social Emotional-Peer Interaction SS,Social Emotional-Self Concept / Social Role SS,Communication-Receptive Communication SS,Communication-Expressive Communication SS,Motor-Gross Motor SS,Motor-Fine Motor SS,Motor-Perceptual Motor SS,Cognitive-Attention and Memory SS,Cognitive-Reasoning / Academic Skills SS,Cognitive-Perception and Concepts SS
count,19494.000000,9698.000000,19489.000000,9694.000000,19486.000000,19485.000000,19472.000000,19483.000000,19481.000000,9688.000000,19484.000000,9693.000000,19482.000000
mean,7.453832,7.957826,10.452409,7.834124,8.032793,6.709110,6.493991,8.621568,9.783430,8.545417,8.407206,8.097803,7.785443
std,3.144153,3.861019,2.834861,3.298726,3.298105,3.622658,3.672590,3.042683,3.191053,3.924365,2.714675,3.203242,3.259881
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,6.000000,5.000000,9.000000,5.000000,6.000000,4.000000,4.000000,7.000000,8.000000,6.000000,7.000000,6.000000,6.000000
50%,7.000000,8.000000,11.000000,8.000000,8.000000,7.000000,6.000000,9.000000,10.000000,9.000000,9.000000,8.000000,8.000000
75%,10.000000,11.000000,12.000000,10.000000,10.000000,9.000000,9.000000,11.000000,12.000000,11.000000,10.000000,11.000000,10.000000
max,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000

In [42]:
dataset_clean.groupby('Program Label')['Child ID'].count()

Program Label
BDI-3 Annual Evaluation                6905
BDI-3 Eligibility Evaluation          12392
BDI-3 Milestone or Exit Evaluation      203
Name: Child ID, dtype: int64

In [16]:
dataset_annual_evaluation = dataset_clean[dataset_clean['Program Label']=='BDI-3 Annual Evaluation']

In [17]:
dataset_annual_evaluation

,Child ID,Gender,Date of Birth,Location - Sub Level 1,Program Label,Adaptive Sum of Scaled Scores,Adaptive Developmental Quotient,Adaptive Percentile Rank,Adaptive 95% Confidence Interval,Adaptive RDI,...,Code 1,Code 2,Code 3,Code 4,Code 5,Code 6,Code 7,Code 8,Code 9,Code 10
19,404042,M,2020-03-17,Upper Cumberland,BDI-3 Annual Evaluation,2.0,46.0,<0.1,42-56,<1/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,419577,F,2021-12-21,East Tennessee,BDI-3 Annual Evaluation,9.0,95.0,37,86-106,79/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,474074,F,2019-11-14,Greater Nashville,BDI-3 Annual Evaluation,21.0,103.0,58,96-110,88/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,474186,F,2019-11-03,Greater Nashville,BDI-3 Annual Evaluation,24.0,112.0,79,104-118,96/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,474641,M,2019-10-29,Upper Cumberland,BDI-3 Annual Evaluation,16.0,88.0,21,82-96,68/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23190,SP02535,F,2021-12-22,Memphis Delta,BDI-3 Annual Evaluation,6.0,80.0,9,73-93,19/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23191,SP02536,F,2022-09-26,Upper Cumberland,BDI-3 Annual Evaluation,8.0,90.0,25,81-101,66/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23192,SP02537,F,2022-11-02,South Central,BDI-3 Annual Evaluation,9.0,95.0,37,86-106,79/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23193,SP02538,M,2021-12-16,Southeast Tennessee,BDI-3 Annual Evaluation,1.0,55.0,0.1,51-71,<1/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23945,SP03290,M,2020-03-25,Memphis Delta,BDI-3 Annual Evaluation,16.0,88.0,21,82-96,66/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
dataset_eligibility_evaluation = dataset_clean[dataset_clean['Program Label']=='BDI-3 Eligibility Evaluation']

In [20]:
dataset_eligibility_evaluation

,Child ID,Gender,Date of Birth,Location - Sub Level 1,Program Label,Adaptive Sum of Scaled Scores,Adaptive Developmental Quotient,Adaptive Percentile Rank,Adaptive 95% Confidence Interval,Adaptive RDI,...,Code 1,Code 2,Code 3,Code 4,Code 5,Code 6,Code 7,Code 8,Code 9,Code 10
0,44879,F,2022-09-27,Southwest,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,39/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,47795,F,2020-12-23,Greater Nashville,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,79/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54340,M,2021-06-22,First Tennessee,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,77/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,54344,F,2022-03-07,Southeast Tennessee,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,54515,M,2021-11-04,Memphis Delta,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,1990-09-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23941,SP03286,F,2021-08-16,Memphis Delta,BDI-3 Eligibility Evaluation,30.0,130.0,98,121-135,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23942,SP03287,F,2023-09-25,Memphis Delta,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23943,SP03288,F,2021-05-18,South Central,BDI-3 Eligibility Evaluation,25.0,115.0,84,107-121,96/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23944,SP03289,F,2021-10-31,South Central,BDI-3 Eligibility Evaluation,21.0,103.0,58,96-110,92/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23946,SP03291,M,2023-09-18,Greater Nashville,BDI-3 Eligibility Evaluation,11.0,105.0,63,94-114,94/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
dataset_exit_evaluation = dataset_clean[dataset_clean['Program Label']=='BDI-3 Milestone or Exit Evaluation']

In [22]:
dataset_exit_evaluation

,Child ID,Gender,Date of Birth,Location - Sub Level 1,Program Label,Adaptive Sum of Scaled Scores,Adaptive Developmental Quotient,Adaptive Percentile Rank,Adaptive 95% Confidence Interval,Adaptive RDI,...,Code 1,Code 2,Code 3,Code 4,Code 5,Code 6,Code 7,Code 8,Code 9,Code 10
60,478244,F,2019-12-04,Upper Cumberland,BDI-3 Milestone or Exit Evaluation,7.0,61.0,1,56-70,18/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,481710,M,2020-03-31,Northwest,BDI-3 Milestone or Exit Evaluation,19.0,97.0,42,90-104,88/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,481768,F,2020-03-07,Upper Cumberland,BDI-3 Milestone or Exit Evaluation,28.0,124.0,95,116-130,98/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,482146,M,2020-04-07,Upper Cumberland,BDI-3 Milestone or Exit Evaluation,4.0,52.0,0.1,48-62,1990-05-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,483511,F,2020-05-09,Southeast Tennessee,BDI-3 Milestone or Exit Evaluation,27.0,121.0,92,113-127,98/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23025,SP02370,M,2020-11-14,East Tennessee,BDI-3 Milestone or Exit Evaluation,16.0,88.0,21,82-96,75/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23026,SP02371,F,2021-02-06,Memphis Delta,BDI-3 Milestone or Exit Evaluation,10.0,70.0,2,65-79,34/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23027,SP02372,F,2020-09-06,Memphis Delta,BDI-3 Milestone or Exit Evaluation,10.0,70.0,2,65-79,29/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23028,SP02373,M,2020-11-22,East Tennessee,BDI-3 Milestone or Exit Evaluation,9.0,67.0,1,62-76,29/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23029,SP02374,M,2020-12-02,East Tennessee,BDI-3 Milestone or Exit Evaluation,13.0,79.0,8,73-87,55/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
dataset_eligibility_evaluation

,Child ID,Gender,Date of Birth,Location - Sub Level 1,Program Label,Adaptive Sum of Scaled Scores,Adaptive Developmental Quotient,Adaptive Percentile Rank,Adaptive 95% Confidence Interval,Adaptive RDI,...,Code 1,Code 2,Code 3,Code 4,Code 5,Code 6,Code 7,Code 8,Code 9,Code 10
0,44879,F,2022-09-27,Southwest,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,39/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,47795,F,2020-12-23,Greater Nashville,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,79/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54340,M,2021-06-22,First Tennessee,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,77/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,54344,F,2022-03-07,Southeast Tennessee,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,54515,M,2021-11-04,Memphis Delta,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,1990-09-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23941,SP03286,F,2021-08-16,Memphis Delta,BDI-3 Eligibility Evaluation,30.0,130.0,98,121-135,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23942,SP03287,F,2023-09-25,Memphis Delta,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,99/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23943,SP03288,F,2021-05-18,South Central,BDI-3 Eligibility Evaluation,25.0,115.0,84,107-121,96/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23944,SP03289,F,2021-10-31,South Central,BDI-3 Eligibility Evaluation,21.0,103.0,58,96-110,92/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23946,SP03291,M,2023-09-18,Greater Nashville,BDI-3 Eligibility Evaluation,11.0,105.0,63,94-114,94/90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
dataset_eligibility_evaluation_subdomains = dataset_eligibility_evaluation.loc[:, ~dataset_eligibility_evaluation.columns.str.contains('CSS')]

In [30]:
dataset_eligibility_evaluation_subdomains = dataset_eligibility_evaluation_corr.loc[:, dataset_eligibility_evaluation_corr.columns.str.contains('SS')]

In [31]:
dataset_eligibility_evaluation_subdomains

,Adaptive-Self Care SS,Adaptive-Personal Responsibility SS,Social Emotional-Adult Interaction SS,Social Emotional-Peer Interaction SS,Social Emotional-Self Concept / Social Role SS,Communication-Receptive Communication SS,Communication-Expressive Communication SS,Motor-Gross Motor SS,Motor-Fine Motor SS,Motor-Perceptual Motor SS,Cognitive-Attention and Memory SS,Cognitive-Reasoning / Academic Skills SS,Cognitive-Perception and Concepts SS
0,7.0,NaN,14.0,NaN,15.0,8.0,9.0,7.0,9.0,NaN,7.0,NaN,13.0
1,7.0,9.0,12.0,9.0,11.0,10.0,9.0,7.0,13.0,11.0,9.0,14.0,7.0
2,8.0,NaN,11.0,NaN,6.0,7.0,7.0,11.0,12.0,NaN,8.0,NaN,7.0
3,13.0,NaN,10.0,NaN,11.0,8.0,8.0,5.0,12.0,NaN,14.0,NaN,10.0
4,5.0,NaN,6.0,NaN,5.0,5.0,5.0,3.0,8.0,NaN,9.0,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23941,17.0,13.0,12.0,12.0,4.0,10.0,7.0,10.0,14.0,14.0,9.0,13.0,13.0
23942,13.0,NaN,13.0,NaN,12.0,12.0,12.0,11.0,15.0,NaN,9.0,NaN,15.0
23943,10.0,15.0,12.0,13.0,13.0,14.0,10.0,15.0,11.0,12.0,13.0,14.0,14.0
23944,10.0,11.0,12.0,10.0,9.0,4.0,1.0,11.0,10.0,11.0,10.0,9.0,10.0
23946,11.0,NaN,9.0,NaN,10.0,8.0,12.0,8.0,12.0,NaN,7.0,NaN,12.0

In [74]:
dataset_eligibility_evaluation_corr_final['standard_deviation'] = dataset_eligibility_evaluation_corr_final.std(axis=1, numeric_only=True)

C:\Users\AaronH\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [75]:
dataset_eligibility_evaluation_corr_final

,Adaptive-Self Care SS,Adaptive-Personal Responsibility SS,Social Emotional-Adult Interaction SS,Social Emotional-Peer Interaction SS,Social Emotional-Self Concept / Social Role SS,Communication-Receptive Communication SS,Communication-Expressive Communication SS,Motor-Gross Motor SS,Motor-Fine Motor SS,Motor-Perceptual Motor SS,Cognitive-Attention and Memory SS,Cognitive-Reasoning / Academic Skills SS,Cognitive-Perception and Concepts SS,standard_deviation
0,7.0,NaN,14.0,NaN,15.0,8.0,9.0,7.0,9.0,NaN,7.0,NaN,13.0,3.218868
1,7.0,9.0,12.0,9.0,11.0,10.0,9.0,7.0,13.0,11.0,9.0,14.0,7.0,2.267383
2,8.0,NaN,11.0,NaN,6.0,7.0,7.0,11.0,12.0,NaN,8.0,NaN,7.0,2.185813
3,13.0,NaN,10.0,NaN,11.0,8.0,8.0,5.0,12.0,NaN,14.0,NaN,10.0,2.803767
4,5.0,NaN,6.0,NaN,5.0,5.0,5.0,3.0,8.0,NaN,9.0,NaN,10.0,2.279132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23941,17.0,13.0,12.0,12.0,4.0,10.0,7.0,10.0,14.0,14.0,9.0,13.0,13.0,3.379804
23942,13.0,NaN,13.0,NaN,12.0,12.0,12.0,11.0,15.0,NaN,9.0,NaN,15.0,1.878238
23943,10.0,15.0,12.0,13.0,13.0,14.0,10.0,15.0,11.0,12.0,13.0,14.0,14.0,1.690850
23944,10.0,11.0,12.0,10.0,9.0,4.0,1.0,11.0,10.0,11.0,10.0,9.0,10.0,3.094660
23946,11.0,NaN,9.0,NaN,10.0,8.0,12.0,8.0,12.0,NaN,7.0,NaN,12.0,1.964971

In [76]:
dataset_eligibility_evaluation_domains = dataset_eligibility_evaluation.loc[:, dataset_eligibility_evaluation.columns.str.contains('Sum of Scaled Scores')]

In [83]:
dataset_eligibility_evaluation_domains = dataset_eligibility_evaluation_domains.drop(columns=['BDI-3 Total Sum of Scaled Scores'])

In [84]:
dataset_eligibility_evaluation_domains['standard_deviation'] = dataset_eligibility_evaluation_domains.std(axis=1, numeric_only=True)

In [85]:
dataset_eligibility_evaluation_domains.describe()

,Adaptive Sum of Scaled Scores,Social-Emotional Sum of Scaled Scores,Communication Sum of Scaled Scores,Motor Sum of Scaled Scores,Cognitive Sum of Scaled Scores,standard_deviation
count,12386.00000,12384.000000,12371.000000,12376.000000,12379.000000,12389.000000
mean,10.57460,21.370236,13.726700,22.043229,19.759674,7.666330
std,5.25707,6.985556,6.420995,7.378779,6.218461,2.039807
min,1.00000,2.000000,2.000000,2.000000,2.000000,0.621916
25%,7.00000,17.000000,9.000000,17.000000,16.000000,6.198339
50%,10.00000,21.000000,14.000000,21.000000,20.000000,7.436905
75%,13.00000,26.000000,19.000000,27.000000,23.000000,9.042180
max,36.00000,48.000000,36.000000,50.000000,47.000000,16.670553

In [82]:
dataset_eligibility_evaluation_domains

,Adaptive Sum of Scaled Scores,Social-Emotional Sum of Scaled Scores,Communication Sum of Scaled Scores,Motor Sum of Scaled Scores,Cognitive Sum of Scaled Scores,BDI-3 Total Sum of Scaled Scores,standard_deviation
0,7.0,29.0,17.0,16.0,20.0,89.0,29.917665
1,16.0,32.0,19.0,31.0,30.0,128.0,42.339895
2,8.0,17.0,14.0,23.0,15.0,77.0,25.609894
3,13.0,21.0,16.0,17.0,24.0,91.0,29.971097
4,5.0,11.0,10.0,11.0,19.0,56.0,18.832596
...,...,...,...,...,...,...,...
23941,30.0,28.0,17.0,38.0,35.0,148.0,48.873988
23942,13.0,25.0,24.0,26.0,24.0,112.0,36.887215
23943,25.0,38.0,24.0,38.0,41.0,166.0,54.690645
23944,21.0,31.0,5.0,32.0,29.0,118.0,39.832985
23946,11.0,19.0,20.0,20.0,19.0,89.0,29.268869

In [91]:
dataset_eligibility_evaluation_adaptive = dataset_eligibility_evaluation[['Adaptive-Self Care SS', 'Adaptive-Personal Responsibility SS']]

In [92]:
dataset_eligibility_evaluation_adaptive.corr()

,Adaptive-Self Care SS,Adaptive-Personal Responsibility SS
Adaptive-Self Care SS,1.000000,0.522434
Adaptive-Personal Responsibility SS,0.522434,1.000000

In [99]:
dataset_eligibility_evaluation_communication = dataset_eligibility_evaluation[['Communication-Receptive Communication SS', 'Communication-Expressive Communication SS']]

In [102]:
dataset_eligibility_evaluation_communication['difference'] = dataset_eligibility_evaluation['Communication-Receptive Communication SS'] - dataset_eligibility_evaluation['Communication-Expressive Communication SS']

C:\Users\AaronH\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [104]:
dataset_eligibility_evaluation_communication.describe()

,Communication-Receptive Communication SS,Communication-Expressive Communication SS,standard_deviation,difference
count,12382.000000,12374.00000,12371.000000,12371.000000
mean,6.938621,6.78964,1.595577,0.146552
std,3.522957,3.54953,1.360892,2.962216
min,1.000000,1.00000,0.000000,-14.000000
25%,4.000000,4.00000,0.707107,-2.000000
50%,7.000000,7.00000,1.414214,0.000000
75%,10.000000,9.00000,2.121320,2.000000
max,19.000000,19.00000,11.313708,16.000000